<?php
class Agent extends Fuel\Core\Agent {};
class Arr extends Fuel\Core\Arr {};
class Asset extends Fuel\Core\Asset {};
class Asset_Instance extends Fuel\Core\Asset_Instance {};
class AttachmentNotFoundException extends Email\AttachmentNotFoundException {};
class Auth extends Auth\Auth {};
class AuthException extends Auth\AuthException {};
abstract class Auth_Acl_Driver extends Auth\Auth_Acl_Driver {};
class Auth_Acl_Ormacl extends Auth\Auth_Acl_Ormacl {};
class Auth_Acl_Simpleacl extends Auth\Auth_Acl_Simpleacl {};
abstract class Auth_Driver extends Auth\Auth_Driver {};
class Auth_Group extends Auth\Model\Auth_Group {};
abstract class Auth_Group_Driver extends Auth\Auth_Group_Driver {};
class Auth_Group_Ormgroup extends Auth\Auth_Group_Ormgroup {};
class Auth_Group_Simplegroup extends Auth\Auth_Group_Simplegroup {};
class Auth_Grouppermission extends Auth\Model\Auth_Grouppermission {};
abstract class Auth_Login_Driver extends Auth\Auth_Login_Driver {};
class Auth_Login_Ormauth extends Auth\Auth_Login_Ormauth {};
class Auth_Login_Simpleauth extends Auth\Auth_Login_Simpleauth {};
class Auth_Metadata extends Auth\Model\Auth_Metadata {};
class Auth_Opauth extends Auth\Auth_Opauth {};
class Auth_Permission extends Auth\Model\Auth_Permission {};
class Auth_Provider extends Auth\Model\Auth_Provider {};
class Auth_Role extends Auth\Model\Auth_Role {};
class Auth_Rolepermission extends Auth\Model\Auth_Rolepermission {};
class Auth_User extends Auth\Model\Auth_User {};
class Auth_Userpermission extends Auth\Model\Auth_Userpermission {};
class Autoloader extends Fuel\Core\Autoloader {};
class Cache extends Fuel\Core\Cache {};
class CacheExpiredException extends Fuel\Core\CacheExpiredException {};
class CacheNotFoundException extends Fuel\Core\CacheNotFoundException {};
interface Cache_Handler_Driver extends Fuel\Core\Cache_Handler_Driver {};
class Cache_Handler_Json extends Fuel\Core\Cache_Handler_Json {};
class Cache_Handler_Serialized extends Fuel\Core\Cache_Handler_Serialized {};
class Cache_Handler_String extends Fuel\Core\Cache_Handler_String {};
class Cache_Storage_Apc extends Fuel\Core\Cache_Storage_Apc {};
abstract class Cache_Storage_Driver extends Fuel\Core\Cache_Storage_Driver {};
class Cache_Storage_File extends Fuel\Core\Cache_Storage_File {};
class Cache_Storage_Memcached extends Fuel\Core\Cache_Storage_Memcached {};
class Cache_Storage_Redis extends Fuel\Core\Cache_Storage_Redis {};
class Cache_Storage_Xcache extends Fuel\Core\Cache_Storage_Xcache {};
class Cli extends Fuel\Core\Cli {};
class Config extends Fuel\Core\Config {};
class ConfigException extends Fuel\Core\ConfigException {};
class Config_Db extends Fuel\Core\Config_Db {};
abstract class Config_File extends Fuel\Core\Config_File {};
class Config_Ini extends Fuel\Core\Config_Ini {};
interface Config_Interface extends Fuel\Core\Config_Interface {};
class Config_Json extends Fuel\Core\Config_Json {};
class Config_Memcached extends Fuel\Core\Config_Memcached {};
class Config_Php extends Fuel\Core\Config_Php {};
class Config_Yml extends Fuel\Core\Config_Yml {};
abstract class Controller extends Fuel\Core\Controller {};
class Controller_Auth extends Api\Controller_Auth {};
abstract class Controller_Hybrid extends Fuel\Core\Controller_Hybrid {};
class Controller_Paginated extends Api\Controller_Paginated {};
abstract class Controller_Rest extends Fuel\Core\Controller_Rest {};
abstract class Controller_Template extends Fuel\Core\Controller_Template {};
class Cookie extends Fuel\Core\Cookie {};
class Crypt extends Fuel\Core\Crypt {};
class DB extends Fuel\Core\DB {};
class DBUtil extends Fuel\Core\DBUtil {};
abstract class Database_Connection extends Fuel\Core\Database_Connection {};
class Database_Dblib_Connection extends Fuel\Core\Database_Dblib_Connection {};
class Database_Exception extends Fuel\Core\Database_Exception {};
class Database_Expression extends Fuel\Core\Database_Expression {};
class Database_MySQL_Connection extends Fuel\Core\Database_MySQL_Connection {};
class Database_MySQLi_Cached extends Fuel\Core\Database_MySQLi_Cached {};
class Database_MySQLi_Connection extends Fuel\Core\Database_MySQLi_Connection {};
class Database_MySQLi_Result extends Fuel\Core\Database_MySQLi_Result {};
class Database_PDO_Cached extends Fuel\Core\Database_PDO_Cached {};
class Database_PDO_Connection extends Fuel\Core\Database_PDO_Connection {};
class Database_PDO_Result extends Fuel\Core\Database_PDO_Result {};
class Database_Query extends Fuel\Core\Database_Query {};
abstract class Database_Query_Builder extends Fuel\Core\Database_Query_Builder {};
class Database_Query_Builder_Delete extends Fuel\Core\Database_Query_Builder_Delete {};
class Database_Query_Builder_Insert extends Fuel\Core\Database_Query_Builder_Insert {};
class Database_Query_Builder_Join extends Fuel\Core\Database_Query_Builder_Join {};
class Database_Query_Builder_Select extends Fuel\Core\Database_Query_Builder_Select {};
class Database_Query_Builder_Update extends Fuel\Core\Database_Query_Builder_Update {};
abstract class Database_Query_Builder_Where extends Fuel\Core\Database_Query_Builder_Where {};
abstract class Database_Result extends Fuel\Core\Database_Result {};
class Database_SQLite_Builder_Delete extends Fuel\Core\Database_SQLite_Builder_Delete {};
class Database_SQLite_Builder_Update extends Fuel\Core\Database_SQLite_Builder_Update {};
class Database_SQLite_Connection extends Fuel\Core\Database_SQLite_Connection {};
class Database_Schema extends Fuel\Core\Database_Schema {};
class Database_Sqlsrv_Connection extends Fuel\Core\Database_Sqlsrv_Connection {};
class Date extends Fuel\Core\Date {};
class Debug extends Fuel\Core\Debug {};
class Email extends Email\Email {};
class EmailSendingFailedException extends Email\EmailSendingFailedException {};
class EmailValidationFailedException extends Email\EmailValidationFailedException {};
abstract class Email_Driver extends Email\Email_Driver {};
class Email_Driver_Mail extends Email\Email_Driver_Mail {};
class Email_Driver_Mailgun extends Email\Email_Driver_Mailgun {};
class Email_Driver_Mandrill extends Email\Email_Driver_Mandrill {};
class Email_Driver_Noop extends Email\Email_Driver_Noop {};
class Email_Driver_Sendmail extends Email\Email_Driver_Sendmail {};
class Email_Driver_Smtp extends Email\Email_Driver_Smtp {};
class Errorhandler extends Fuel\Core\Errorhandler {};
abstract class Event extends Fuel\Core\Event {};
class Event_Instance extends Fuel\Core\Event_Instance {};
class Fieldset extends Fuel\Core\Fieldset {};
class Fieldset_Field extends Fuel\Core\Fieldset_Field {};
class File extends Fuel\Core\File {};
class FileAccessException extends Fuel\Core\FileAccessException {};
class File_Area extends Fuel\Core\File_Area {};
class File_Handler_Directory extends Fuel\Core\File_Handler_Directory {};
class File_Handler_File extends Fuel\Core\File_Handler_File {};
class Finder extends Fuel\Core\Finder {};
class Form extends Fuel\Core\Form {};
class Form_Instance extends Fuel\Core\Form_Instance {};
class Format extends Fuel\Core\Format {};
class Ftp extends Fuel\Core\Ftp {};
class FtpConnectionException extends Fuel\Core\FtpConnectionException {};
class FtpFileAccessException extends Fuel\Core\FtpFileAccessException {};
class Fuel extends Fuel\Core\Fuel {};
class FuelException extends Fuel\Core\FuelException {};
class Html extends Fuel\Core\Html {};
class HttpBadRequestException extends Fuel\Core\HttpBadRequestException {};
abstract class HttpException extends Fuel\Core\HttpException {};
class HttpNoAccessException extends Fuel\Core\HttpNoAccessException {};
class HttpNotFoundException extends Fuel\Core\HttpNotFoundException {};
class HttpServerErrorException extends Fuel\Core\HttpServerErrorException {};
class Image extends Fuel\Core\Image {};
abstract class Image_Driver extends Fuel\Core\Image_Driver {};
class Image_Gd extends Fuel\Core\Image_Gd {};
class Image_Imagemagick extends Fuel\Core\Image_Imagemagick {};
class Image_Imagick extends Fuel\Core\Image_Imagick {};
class Inflector extends Fuel\Core\Inflector {};
class Input extends Fuel\Core\Input {};
class Input_Instance extends Fuel\Core\Input_Instance {};
class InvalidAttachmentsException extends Email\InvalidAttachmentsException {};
class InvalidEmailStringEncoding extends Email\InvalidEmailStringEncoding {};
class InvalidPathException extends Fuel\Core\InvalidPathException {};
class Lang extends Fuel\Core\Lang {};
class LangException extends Fuel\Core\LangException {};
class Lang_Db extends Fuel\Core\Lang_Db {};
abstract class Lang_File extends Fuel\Core\Lang_File {};
class Lang_Ini extends Fuel\Core\Lang_Ini {};
interface Lang_Interface extends Fuel\Core\Lang_Interface {};
class Lang_Json extends Fuel\Core\Lang_Json {};
class Lang_Php extends Fuel\Core\Lang_Php {};
class Lang_Yml extends Fuel\Core\Lang_Yml {};
class Log extends Fuel\Core\Log {};
class Markdown extends Fuel\Core\Markdown {};
class Migrate extends Fuel\Core\Migrate {};
class Model extends Fuel\Core\Model {};
class Model_Crud extends Fuel\Core\Model_Crud {};
class Module extends Fuel\Core\Module {};
class ModuleNotFoundException extends Fuel\Core\ModuleNotFoundException {};
class Mongo_Db extends Fuel\Core\Mongo_Db {};
class Mongo_DbException extends Fuel\Core\Mongo_DbException {};
class Num extends Fuel\Core\Num {};
class OpauthException extends Auth\OpauthException {};
class OutsideAreaException extends Fuel\Core\OutsideAreaException {};
class Package extends Fuel\Core\Package {};
class PackageNotFoundException extends Fuel\Core\PackageNotFoundException {};
class Pagination extends Fuel\Core\Pagination {};
class PhpErrorException extends Fuel\Core\PhpErrorException {};
abstract class Presenter extends Fuel\Core\Presenter {};
class Profiler extends Fuel\Core\Profiler {};
class RedisException extends Fuel\Core\RedisException {};
class Redis_Db extends Fuel\Core\Redis_Db {};
class Request extends Fuel\Core\Request {};
class RequestException extends Fuel\Core\RequestException {};
class RequestStatusException extends Fuel\Core\RequestStatusException {};
class Request_Curl extends Fuel\Core\Request_Curl {};
abstract class Request_Driver extends Fuel\Core\Request_Driver {};
class Request_Soap extends Fuel\Core\Request_Soap {};
class Response extends Fuel\Core\Response {};
abstract class Response_Base extends Api\Response_Base {};
class Response_Paginated extends Api\Response_Paginated {};
class Response_Status extends Api\Response_Status {};
class Route extends Fuel\Core\Route {};
class Router extends Fuel\Core\Router {};
interface Sanitization extends Fuel\Core\Sanitization {};
class Security extends Fuel\Core\Security {};
class SecurityException extends Fuel\Core\SecurityException {};
class SendmailConnectionException extends Email\SendmailConnectionException {};
class SendmailFailedException extends Email\SendmailFailedException {};
class Session extends Fuel\Core\Session {};
class Session_Cookie extends Fuel\Core\Session_Cookie {};
class Session_Db extends Fuel\Core\Session_Db {};
abstract class Session_Driver extends Fuel\Core\Session_Driver {};
class Session_Exception extends Fuel\Core\Session_Exception {};
class Session_File extends Fuel\Core\Session_File {};
class Session_Memcached extends Fuel\Core\Session_Memcached {};
class Session_Redis extends Fuel\Core\Session_Redis {};
class SimpleUserUpdateException extends Auth\SimpleUserUpdateException {};
class SimpleUserWrongPassword extends Auth\SimpleUserWrongPassword {};
class SmtpAuthenticationFailedException extends Email\SmtpAuthenticationFailedException {};
class SmtpCommandFailureException extends Email\SmtpCommandFailureException {};
class SmtpConnectionException extends Email\SmtpConnectionException {};
class SmtpTimeoutException extends Email\SmtpTimeoutException {};
class Str extends Fuel\Core\Str {};
abstract class TestCase extends Fuel\Core\TestCase {};
class Theme extends Fuel\Core\Theme {};
class ThemeException extends Fuel\Core\ThemeException {};
class Unzip extends Fuel\Core\Unzip {};
class Upload extends Fuel\Core\Upload {};
class Uri extends Fuel\Core\Uri {};
class Validation extends Fuel\Core\Validation {};
class Validation_Error extends Fuel\Core\Validation_Error {};
class View extends Fuel\Core\View {};
abstract class Viewmodel extends Fuel\Core\Viewmodel {};